function ObjFcn = makeObjFcn(XTrain,YTrain,XValidation,YValidation,varargin)
A.solver='sgdm';
A.R2loss=0;
A.path='/data/project2/yangsi/analysis/n2oFluxPaper/train/RF/production/allinone/optimout/';
A=parse_pv_pairs(A,varargin);
ObjFcn = @valErrorFun;
    function [valError,cons,fileName] = valErrorFun(optVars)

   tstart=datetime('15-Sep-2019','Locale','en_US');
   tend=datetime('05-Jan-2020','Locale','en_US')
   ttime=timerange(tstart,tend,'closed');
   Rroot='/home/euphotic_/yangino-bot/';
   addpath(genpath(Rroot));
   [~,TMW]=IngestBinance('rroot',Rroot);
   [varnames,tmw] = TA.strat1(TMW.h,'Timeindex', ttime,...
      'rfper', optVars.rfper,...
      'rfmult', optVars.rfmult,...
      'rsiper', optVars.rsiper,...
      'jmaL', optVars.jmaL,...
      'jmaphi', optVars.jmaphi,...
      'jmapow',optVars.jmapow,...
      'atrper', optVars.atrper,...
      'sarinc', optVars.sarinc,...
      'sarmmax', optVars.sarmmax,...
      'svolper', optVars.svolper,...
      'svolf', optVars.svolf,...
      );

   [gains, drawdown] = cryptoSimulation_andyopt('tp1',optVars.tp1,...
      'tp2',optVars.tp2, ...
      'dnSL', optVars.dnSL,...
      'slfix', optVars.slfix,...
      'slscale1', optVars.slscale1,...
      'slscale2', optVats.slscale2,...
      'lstop', optVars.lstop,...
      'sstop',optVars.sstop)

   %tables
   if drawdown>0.33
      valError = 10^20;
   else
      valError = -gains;
   end

   cons = [];
   fileName = [];
end
end
