function ObjFcn = makeObjFcn(varargin)
A.onlysim = 0;

ObjFcn = @valErrorFun;
    function [valError,cons,fileName] = valErrorFun(optVars)

   tstart=datetime('01-Nov-2019','Locale','en_US');
   tend=datetime('05-Jan-2200','Locale','en_US')
   ttime=timerange(tstart,tend,'closed');
   Rroot='/home/euphotic_/yangino-bot/';
   addpath(genpath(Rroot));
   [~,TMW]=IngestBinance('rroot',Rroot);
   if ~ A.onlysim
      [varnames,tmw] = TA.strat1(TMW.h,'Timeindex', ttime,...
         'rfper', optVars.rfper,...
         'rfmult', optVars.rfmult,...
         'rsiper', optVars.rsiper,...
         'adxper',optVars.adxper,...
         'macdfast',optVars.macdfast,...
         'macdsignal',optVars.macdsignal,...
         'macdlong', optVars.macdlong,...
         'bollper', optVars.bollper,...
         'jmaL', optVars.jmaL,...
         'jmaphi', optVars.jmaphi,...
         'jmapow',optVars.jmapow,...
         'sarinc', optVars.sarinc,...
         'sarmmax', optVars.sarmmax,...
         'svolper', optVars.svolper,...
         'svolf', optVars.svolf...
         );
   else
         [varnames,tmw] = TA.strat1(TMW.h,'Timeindex', ttime,'atrper', 15);
   end

   [gains, drawdown,~,~] = cryptoSimulation_andyopt(tmw,...
      'slscale1', optVars.slscale1,...
      'slscale2', optVars.slscale2,...
      'slscale3', optVars.slscale3,...
      'slscale4', optVars.slscale4,...
      'prelstop', optVars.lstop,...
      'presstop', optVars.sstop,...
      'slmax', optVars.slmax,...
      'adxth',optVars.adxth,...
      'rsiobos',optVars.rsiobos);
%      'tp1',optVars.tp1,...
%      'tp2',optVars.tp2, ...
%      'tp1scale',optVars.tp1scale, ...
%      'tp2scale',optVars.tp2scale, ...
%      'dnSL', optVars.dnSL,...

   %tables
   if drawdown>25
      valError = 10000
   else
      valError = -gains;
   end

   valError = -sign(gains).*(gains.^2) + (drawdown).^6.5

   valError(valError==inf)=10000.^2;
   valError(isnan(valError))=10000.^2;

   cons = [];
   fileName = [];
end
end
