function sig = FireSignalWithBB(varargin)
% % % % % % % % %  
% Fires Long and Short signals for use by the python Bot
%
% --Optional args 
% ---------------
A.rroot = '/home/euphotic_/yangino-bot/';
A.model='strat1';
A.PredTimeIndex = timerange(datetime('01-Feb-2020',...
   'Locale','en_US'),datetime('01-Jan-2200','Locale','en_US'),'closed');
A.Xwin=1;
A.strat=2;
A=parse_pv_pairs(A,varargin); % parse varargin
% ---------------

% retreive historical data
addpath(genpath(A.rroot));
[~,TMW]=IngestBinance('rroot',A.rroot);

% Calculate technical indicators
tlast = TMW.h.Time(end);

tnow = datetime(now-1/24,'ConvertFrom','datenum');
dt = tnow-tlast;
volScale = 60.0/minutes(dt);
TMW.h.Volume(end) = TMW.h.Volume(end).*volScale;
%[varnames,tmw] = TA.strat1(TMW.h,'Timeindex', A.PredTimeIndex);
%[varnames,tmw] = TA.strat1(TMW.h,'Timeindex', A.PredTimeIndex,...
%   'rfper',15,...
%   'rfmult',1.68,...
%   'rsiper',18,...
%   'jmaL',22,...
%   'jmaphi', 70,...
%   'jmapow',2.8837,...
%   'adxper',19,...
%   'bollper',13,...
%   'macdfast',9,...
%   'macdsignal',12,...
%   'macdlong',12,...
%   'sarinc',0.65,...
%   'sarmmax',0.041,...
%   'svolper',42,...
%   'svolf',1.77 ...
%   );

[varnames,tmw] = TA.strat1(TMW.h,'Timeindex', A.PredTimeIndex,...
   'rfper',35,...
   'rfmult',1.773387316083307,...
   'rsiper',20,...
   'jmaL',16,...
   'jmaphi', 37,...
   'jmapow',2.667985158500809,...
   'adxper',19,...
   'bollper',19,...
   'macdfast',6,...
   'macdsignal',2,...
   'macdlong',13,...
   'sarinc',0.136927458933461,...
   'sarmmax',0.109025275697910,...
   'svolper',59,...
   'svolf',2.0 ...
   );
% Get long and short signals
[long, short] = strategy(tmw, 'strat', 'Andy','adxth',5,'rsiobos',74.30);
%[long, short] = strategy(tmw, 'strat', 'Andy','adhth',5,'rsiobos',74.26);



presig = zeros(size(long));
presig(long)=1;
presig(short)=-1;
if A.strat==1
   sig = presig(end-A.Xwin:end);
elseif A.strat==2
   lo = tmw.fbolllo;
   up = tmw.fbollup;
   sig = [presig(end-A.Xwin:end),lo(end-A.Xwin:end),up(end-A.Xwin:end)];
end

